### PR TITLE
Clustering/regular models

### PR DESCRIPTION
**Pull request by AHReccese**
#### Reference Issues/PRs
#17 
#### What does this implement/fix? Explain your changes.
add support for these clustering models:
* AffinityPropagation
* MeanShift
* SpectralClustering
* AgglomerativeClustering
* DBSCAN
* OPTICS
* GaussianMixture

### CODE REVIEW

**Comment by AHReccese** [comment]
Hi, dear Sepand, I hope you're doing well, since it is a minor PR, you can review it till 11/04/2023.
@sepandhaghighi

**Review by sadrasabouri — APPROVED** [review]
LGTM :rocket:

**Comment by AHReccese** [comment]
@sepandhaghighi 
considered time for minor PR review has been finished.
please review this PR ASAP.

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi considered time for minor PR review has been finished. please review this PR ASAP.

Thanks for your reminder 🔥

**Review by sepandhaghighi — CHANGES_REQUESTED** [review]
@AHReccese If required, could you kindly update the `CHANGELOG.md`?

**Comment by AHReccese** [comment]
@sepandhaghighi I think I've done it.
What do you mean exactly?

**Comment by AHReccese** [comment]
@sepandhaghighi 
you are right, unfortunately, I forgot to push the last commit :)).
done.

**Review by sepandhaghighi — APPROVED** [review]
🚀

**Pull request merged**
