### PR TITLE
minor refactorings in naming conventions

### PR DESCRIPTION
**Pull request by AHReccese**
#### Reference Issues/PRs
Minor Enhancements on naming convension

### CODE REVIEW

**Review by sadrasabouri — APPROVED** [review]
LGTM, but it is extermely hard to understand the changes. I'm relying on the fact that tests are running well.

**Comment by AHReccese** [comment]
Extremely hard?! weird!

**Comment by sadrasabouri** [comment]
> Extremely hard?! weird! @sadrasabouri

Yes.
BTW, you can merge it anytime. I just stopped merging it due to the several opened PRs originating from the same branch. Please merge them cautiously.

**Comment by AHReccese** [comment]
Each PR should definitely get reviewed without relying on anything else.
If it's hard, we can have a meeting to clarify the details. Let me know your time availability.

**Comment by AHReccese** [comment]
I've sent you a video regarding this PR, I hope it clarifies it well.
Let me know if you have any other questions.
@sadrasabouri

**Comment by AHReccese** [comment]
> > Extremely hard?! weird! @sadrasabouri
> 
> Yes. BTW, you can merge it anytime. I just stopped merging it due to the several opened PRs originating from the same branch. Please merge them cautiously.

Don't worry, after you completely finish your review, I will take care of merging.

**Review by sadrasabouri — APPROVED** [review]
LGTM now after the clarification video

**Comment by sadrasabouri** [comment]
I accidentally merged it, I opened a revert branch but you can remove that branch and update other PRs with current `dev`.

**Comment by AHReccese** [comment]
Don't worry pal, We good.
@sadrasabouri

**Pull request merged**
