### PR TITLE
Minor edits

### PR DESCRIPTION
**Pull request by sepandhaghighi**
#### What does this implement/fix? Explain your changes.
- `README.md` TOC removed
- `SUPPORTED_MODELS.md` TOC removed
- Badges bug fixed

### CODE REVIEW

**Comment by AHReccese** [comment]
LGTM
@sepandhaghighi

**Comment by AHReccese** [comment]
I know that now, we can still traverse to the section with # at the end of the URL, but still, for indexing purposes, we do need the TOC, don't we? to find out what we have in this file.
@sepandhaghighi

**Review by AHReccese — CHANGES_REQUESTED** [review]
Thank you, I didn't find anything wrong in this PR, but I still have the indexing question.

**Comment by sepandhaghighi** [comment]
> I know that now, we can still traverse to the section with # at the end of the URL, but still, for indexing purposes, we do need the TOC, don't we? to find out what we have in this file. @sepandhaghighi

Recently, GitHub implemented its own automatic table of contents, making our manual TOC unnecessary.

image

**Comment by AHReccese** [comment]
Impressive, I thought maybe legacy users(like me :) not you) may not find this out.
I myself didn't see the compressed menu icon.
@sepandhaghighi

**Comment by AHReccese** [comment]
another question, as you know we've defined the TOC part as the way we wanted it to be, like referring to the Authors.md file(although it doesn't have a specific part in the README itself) and GitHub doesn't completely make it just like ours, it just extracts some important HTML tags.

**Review by AHReccese — CHANGES_REQUESTED** [review]
another question, as you know we've defined the TOC part as the way we wanted it to be, like referring to the Authors.md file(although it doesn't have a specific part in the README itself) and GitHub doesn't completely make it just like ours, it just extracts some important HTML tags.

What's your idea here? Updating the readme file to have the exact same TOC(with GitHub's generated one I mean)
@sepandhaghighi

**Comment by sepandhaghighi** [comment]
> Another question, as you know we've defined the TOC part as the way we wanted it to be, like referring to the Authors.md file(although it doesn't have a specific part in the README itself) and GitHub doesn't completely make it just like ours, it just extracts some important HTML tags.
> 
> What's your idea here? Updating the readme file to have the exact same TOC(with GitHub's generated one I mean) @sepandhaghighi

It's not my taste.
Increasing the manual portion of a document can lead to a higher number of bugs.

**Review by AHReccese — APPROVED** [review]

**Pull request merged**
